version: "3.7"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - config/database.env
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
  profile:
    build:
      context: ProfileService
      dockerfile: Dockerfile
    ports:
      - "8889:8889"
    restart: always
    depends_on:
      - postgresql
  auth:
    build:
      context: AuthService
      dockerfile: Dockerfile
    ports:
      - "8887:8887"
    restart: always
    depends_on:
      - redis
  user_facade:
    build:
      context: UserFacade
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - profile
      - auth