basePath: /
definitions:
  handlerErrors.Error:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
  handlersDto.AuthOutDto:
    properties:
      userID:
        type: integer
      userMail:
        type: string
      userRole:
        type: string
      userSurname:
        type: string
      username:
        type: string
    type: object
  profile.ProfileData:
    properties:
      UserID:
        type: integer
      UserMail:
        type: string
      UserName:
        type: string
      UserRole:
        type: string
      UserSurname:
        type: string
    type: object
  user.RegisterUser:
    properties:
      password:
        type: string
      userName:
        type: string
    type: object
  user.User:
    properties:
      username:
        type: string
    type: object
host: https://localhost:8080
info:
  contact: {}
  description: This is a backend API
  title: SIF Backend API
  version: "0.5"
paths: {}
swagger: "2.0"
